//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int ID { get; set; }
        public string table_nm { get; set; }
        public int record_id { get; set; }
        public System.DateTime time_stamp { get; set; }
        public string tran_type { get; set; }
        public string field_nm { get; set; }
        public Nullable<int> consultant_id { get; set; }
    }
}
