//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.consultant_employment_history = new HashSet<consultant_employment_history>();
            this.exps = new HashSet<exp>();
            this.sows = new HashSet<sow>();
        }

        public int ID { get; set; }
        [Display(Name = "Name")]
        public string company_nm { get; set; }
        [Display(Name = "Location")]
        public string company_location { get; set; }
        [Display(Name = "Is a Client?")]
        public bool is_client { get; set; }
        [Display(Name = "Description")]
        public string company_descr { get; set; }
        [Display(Name = "Short Name")]
        public string company_short_nm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consultant_employment_history> consultant_employment_history { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exp> exps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sow> sows { get; set; }
    }
}
