//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_info
    {
        public int ID { get; set; }
        public string company_nm { get; set; }
        public string owner_nm { get; set; }
        public string owner_title { get; set; }
        public string app_owner { get; set; }
        public string app_owner_title { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string phone_number { get; set; }
        public string fax_number { get; set; }
        public string website { get; set; }
        public string home_page_greeting { get; set; }
        public string zip_code { get; set; }
        public string sharepoint_site { get; set; }
        public Nullable<int> meradia_globe { get; set; }
        public Nullable<int> sow_id { get; set; }
    
        public virtual sow sow { get; set; }
    }
}
