//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultant_skill
    {
        public int ID { get; set; }
        public int consultant_id { get; set; }
        public int skill_id { get; set; }
        public int order_nbr { get; set; }
        public bool suppressed { get; set; }
        public Nullable<int> proficiency_id { get; set; }
        public string suppressed_RIC { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual proficiency proficiency { get; set; }
        public virtual skill skill { get; set; }
    }
}
