//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_layout_grp
    {
        public int ID { get; set; }
        public int exp_layout_id { get; set; }
        public int order_nbr { get; set; }
        public bool suppressed { get; set; }
        public string sort1_val { get; set; }
        public string sort2_val { get; set; }
        public string sort3_val { get; set; }
        public string sort1_nm { get; set; }
        public string sort2_nm { get; set; }
        public string sort3_nm { get; set; }
        public string group_nm { get; set; }
        public bool show_companies { get; set; }
        public string sort_def { get; set; }
    
        public virtual exp_layout exp_layout { get; set; }
    }
}
