//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_layout_grp_dtl
    {
        public int ID { get; set; }
        public int exp_layout_grp_id { get; set; }
        public int exp_detail_id { get; set; }
        public Nullable<int> order_nbr { get; set; }
        public bool suppressed { get; set; }
        public string detail_txt { get; set; }
        public string user_nm { get; set; }
    
        public virtual exp_detail exp_detail { get; set; }
    }
}
