//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class experience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public experience()
        {
            this.experience_detail = new HashSet<experience_detail>();
        }
    
        public int ID { get; set; }
        public int consultant_id { get; set; }
        public int sow_id { get; set; }
        public string tags { get; set; }
        public int order_nbr { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual sow sow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experience_detail> experience_detail { get; set; }
    }
}
