//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noteworthy_sow
    {
        public int ID { get; set; }
        public Nullable<int> consultant_id { get; set; }
        public Nullable<int> sow_id { get; set; }
        public int order_nbr { get; set; }
        public bool suppressed { get; set; }
        public string project_nm { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual sow sow { get; set; }
    }
}
