//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sow()
        {
            this.company_info = new HashSet<company_info>();
            this.exps = new HashSet<exp>();
            this.experiences = new HashSet<experience>();
            this.noteworthy_sow = new HashSet<noteworthy_sow>();
            this.sow_consultant = new HashSet<sow_consultant>();
            this.timeslips = new HashSet<timeslip>();
            this.timeslip_phase = new HashSet<timeslip_phase>();
        }
    
        public int ID { get; set; }
        public string sow_id { get; set; }
        public int company_id { get; set; }
        public string project_nm { get; set; }
        public int project_type_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> start_dt { get; set; }
        public Nullable<System.DateTime> end_dt { get; set; }
        public Nullable<int> master_sow { get; set; }
        public bool meradia_sow { get; set; }
        public Nullable<int> domain_id { get; set; }
        public Nullable<System.DateTime> intro_dt { get; set; }
        public Nullable<int> intro_con { get; set; }
        public bool active_sow { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_info> company_info { get; set; }
        public virtual consultant consultant { get; set; }
        public virtual domain domain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exp> exps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experience> experiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<noteworthy_sow> noteworthy_sow { get; set; }
        public virtual project_type project_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sow_consultant> sow_consultant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeslip> timeslips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timeslip_phase> timeslip_phase { get; set; }
    }
}
