//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sow_consultant
    {
        public int ID { get; set; }
        public int sow_id { get; set; }
        public int consultant_id { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual sow sow { get; set; }
    }
}
