//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class speaking_engagement
    {
        public int ID { get; set; }
        public Nullable<int> consultant_id { get; set; }
        public string event_nm { get; set; }
        public string event_location { get; set; }
        public Nullable<System.DateTime> event_dt { get; set; }
        public string event_topic { get; set; }
        public int order_nbr { get; set; }
        public bool suppressed { get; set; }
        public Nullable<int> event_role { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual event_role event_role1 { get; set; }
    }
}
