//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thought_leadership
    {
        public int ID { get; set; }
        public Nullable<int> consultant_id { get; set; }
        public string thought_leadership_nm { get; set; }
    }
}
