//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class timeslip
    {
        public int ID { get; set; }
        public int consultant_id { get; set; }
        public int sow_id { get; set; }
        public System.DateTime slip_start_dt { get; set; }
        public Nullable<int> slip_phase_nm { get; set; }
        public string slip_location { get; set; }
        public string slip_desc { get; set; }
        public System.DateTime slip_end_dt { get; set; }
        public string slip_status { get; set; }
        public decimal slip_time { get; set; }
        public string slip_task_nm { get; set; }
        public string slip_bill_status { get; set; }
    
        public virtual consultant consultant { get; set; }
        public virtual sow sow { get; set; }
        public virtual timeslip_phase timeslip_phase { get; set; }
    }
}
