//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class white_paper
    {
        public int ID { get; set; }
        public Nullable<int> consultant_id { get; set; }
        public string white_paper_title { get; set; }
        public System.DateTime white_paper_dt { get; set; }
        public string description { get; set; }
        public bool suppressed { get; set; }
        public Nullable<int> order_nbr { get; set; }
    
        public virtual consultant consultant { get; set; }
    }
}
